-- Migración V1: Crear tabla despachos
-- Fecha: 2026-05-13
-- Descripción: Crear tabla base de despachos con validación de unicidad por numero_pedido

CREATE TABLE despachos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_pedido BIGINT NOT NULL,
    tipo_despacho VARCHAR(50) NOT NULL,
    transportista VARCHAR(255) NOT NULL,
    fecha_despacho TIMESTAMP NOT NULL,
    tracking_code VARCHAR(255) NOT NULL,
    CONSTRAINT uk_despachos_numero_pedido UNIQUE (numero_pedido)
);

