server.port=8084
services.pedido.url=http://localhost:8081

spring.application.name=despacho-service
spring.datasource.url=jdbc:h2:mem:despacho_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


