spring.application.name=sistema-gestion-pedidos
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/gestion_pedidos
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false