spring.application.name=fabricacion-service
spring.profiles.active=h2

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

services.pedido.url=${PEDIDO_SERVICE_URL:http://localhost:8081}

spring.cloud.openfeign.client.config.default.connectTimeout=${FEIGN_CONNECT_TIMEOUT_MS:3000}
spring.cloud.openfeign.client.config.default.readTimeout=${FEIGN_READ_TIMEOUT_MS:5000}
