spring.application.name=metrica-service
spring.profiles.active=h2

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

services.cliente.url=${CLIENTE_SERVICE_URL:http://localhost:8082}
services.pedido.url=${PEDIDO_SERVICE_URL:http://localhost:8081}
