CREATE TABLE IF NOT EXISTS ordenes_fabricacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL UNIQUE,
    estado_fabricacion VARCHAR(50) NOT NULL DEFAULT 'EN_PROCESO',
    fecha_inicio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_fin TIMESTAMP NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP NULL,
    descripcion_estado VARCHAR(500),
    usuario_responsable VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS historial_fabricacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_fabricacion_id BIGINT NOT NULL,
    estado_anterior VARCHAR(50),
    estado_nuevo VARCHAR(50) NOT NULL,
    fecha_cambio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuario_id VARCHAR(255),
    motivo VARCHAR(500),
    FOREIGN KEY (orden_fabricacion_id) REFERENCES ordenes_fabricacion(id) ON DELETE CASCADE
);

ALTER TABLE historial_fabricacion ALTER COLUMN estado_anterior DROP NOT NULL;
