spring.application.name=pedido-service
spring.profiles.active=h2

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

services.cliente.url=http://localhost:8082
services.producto.url=http://localhost:8083
services.estado.url=http://localhost:8086